AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function ListBucketsCommand.
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonKinesisFullAccess
      Path: /
  primer:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.7
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn
      Handler: index.handler
      Code:
        ZipFile: |
          import json
          import boto3
          def lambda_handler(event, context):
              # TODO implement
              print("this is for lambda fn demo with  s3 events")
              dynamodb_client = boto3.client("dynamodb")
              table_name = "orders"
              response = dynamodb_client.put_item(
                TableName=table_name,
                Item={
                  "order_id": {"S": "ord12345"},
                  "order_date": {"S": "2023-09-03"},
                  "user_email": {"S": "test@vytec.com"},
                  "amount": {"N": "120"},
                },
              )

              print(response)
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from Lambda!')
              }
      Description: List Amazon S3 buckets in us-east-1.
      TracingConfig:
        Mode: Active
  myDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "order_id"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "order_id"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "myTableName"